#! /bin/sh
### BEGIN INIT INFO
# Provides:          hapiweb
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: hapiweb
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

if [ ! -d "/var/www/hapi/" ]; then
  sudo mkdir -p "/var/www/hapi/"
fi

sudo /usr/bin/shellinaboxd -p 4200 --disable-ssl -b
(cd /var/www/hapi; sudo python -m SimpleHTTPServer 80) &
